CREATE TABLE materials (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    r_code VARCHAR(50) NOT NULL UNIQUE,
    material_type VARCHAR(50),
    data JSON,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);